version: '3.8'
services:
  auth:
    build: ./services/auth
    ports:
      - "5100:5100" # http
      - "5101:5101" # grpc
    environment:
      - PORT=5100

  file:
    build: ./services/file
    ports:
      - "5200:5200"
    environment:
      - PORT=5200

  sharing:
    build: ./services/sharing
    ports:
      - "5300:5300"
    environment:
      - PORT=5300

  gateway:
    build: ./services/gateway
    ports:
      - "8080:8080"
    environment:
      - AUTH_ADDR=http://auth:5100
      - AUTH_GRPC_ADDR=auth:5101
      - FILE_ADDR=http://file:5200
      - SHARE_ADDR=http://sharing:5300
