// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: sharing.proto

package sharingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SharingService_ShareFile_FullMethodName      = "/sharing.SharingService/ShareFile"
	SharingService_GetSharedFiles_FullMethodName = "/sharing.SharingService/GetSharedFiles"
)

// SharingServiceClient is the client API for SharingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SharingServiceClient interface {
	ShareFile(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*ShareResponse, error)
	GetSharedFiles(ctx context.Context, in *GetSharedRequest, opts ...grpc.CallOption) (*GetSharedResponse, error)
}

type sharingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSharingServiceClient(cc grpc.ClientConnInterface) SharingServiceClient {
	return &sharingServiceClient{cc}
}

func (c *sharingServiceClient) ShareFile(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*ShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareResponse)
	err := c.cc.Invoke(ctx, SharingService_ShareFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sharingServiceClient) GetSharedFiles(ctx context.Context, in *GetSharedRequest, opts ...grpc.CallOption) (*GetSharedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSharedResponse)
	err := c.cc.Invoke(ctx, SharingService_GetSharedFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SharingServiceServer is the server API for SharingService service.
// All implementations must embed UnimplementedSharingServiceServer
// for forward compatibility.
type SharingServiceServer interface {
	ShareFile(context.Context, *ShareRequest) (*ShareResponse, error)
	GetSharedFiles(context.Context, *GetSharedRequest) (*GetSharedResponse, error)
	mustEmbedUnimplementedSharingServiceServer()
}

// UnimplementedSharingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSharingServiceServer struct{}

func (UnimplementedSharingServiceServer) ShareFile(context.Context, *ShareRequest) (*ShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShareFile not implemented")
}
func (UnimplementedSharingServiceServer) GetSharedFiles(context.Context, *GetSharedRequest) (*GetSharedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSharedFiles not implemented")
}
func (UnimplementedSharingServiceServer) mustEmbedUnimplementedSharingServiceServer() {}
func (UnimplementedSharingServiceServer) testEmbeddedByValue()                        {}

// UnsafeSharingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SharingServiceServer will
// result in compilation errors.
type UnsafeSharingServiceServer interface {
	mustEmbedUnimplementedSharingServiceServer()
}

func RegisterSharingServiceServer(s grpc.ServiceRegistrar, srv SharingServiceServer) {
	// If the following call panics, it indicates UnimplementedSharingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SharingService_ServiceDesc, srv)
}

func _SharingService_ShareFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharingServiceServer).ShareFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SharingService_ShareFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharingServiceServer).ShareFile(ctx, req.(*ShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SharingService_GetSharedFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSharedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharingServiceServer).GetSharedFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SharingService_GetSharedFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharingServiceServer).GetSharedFiles(ctx, req.(*GetSharedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SharingService_ServiceDesc is the grpc.ServiceDesc for SharingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SharingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sharing.SharingService",
	HandlerType: (*SharingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShareFile",
			Handler:    _SharingService_ShareFile_Handler,
		},
		{
			MethodName: "GetSharedFiles",
			Handler:    _SharingService_GetSharedFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sharing.proto",
}
