// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: sharing.proto

package sharingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	SharedWith    string                 `protobuf:"bytes,3,opt,name=shared_with,json=sharedWith,proto3" json:"shared_with,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareRequest) Reset() {
	*x = ShareRequest{}
	mi := &file_sharing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareRequest) ProtoMessage() {}

func (x *ShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareRequest.ProtoReflect.Descriptor instead.
func (*ShareRequest) Descriptor() ([]byte, []int) {
	return file_sharing_proto_rawDescGZIP(), []int{0}
}

func (x *ShareRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ShareRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ShareRequest) GetSharedWith() string {
	if x != nil {
		return x.SharedWith
	}
	return ""
}

type ShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareResponse) Reset() {
	*x = ShareResponse{}
	mi := &file_sharing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareResponse) ProtoMessage() {}

func (x *ShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sharing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareResponse.ProtoReflect.Descriptor instead.
func (*ShareResponse) Descriptor() ([]byte, []int) {
	return file_sharing_proto_rawDescGZIP(), []int{1}
}

func (x *ShareResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ShareResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ShareResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetSharedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSharedRequest) Reset() {
	*x = GetSharedRequest{}
	mi := &file_sharing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSharedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSharedRequest) ProtoMessage() {}

func (x *GetSharedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSharedRequest.ProtoReflect.Descriptor instead.
func (*GetSharedRequest) Descriptor() ([]byte, []int) {
	return file_sharing_proto_rawDescGZIP(), []int{2}
}

func (x *GetSharedRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SharedFileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	SharedAt      int64                  `protobuf:"varint,3,opt,name=shared_at,json=sharedAt,proto3" json:"shared_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharedFileInfo) Reset() {
	*x = SharedFileInfo{}
	mi := &file_sharing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedFileInfo) ProtoMessage() {}

func (x *SharedFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sharing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedFileInfo.ProtoReflect.Descriptor instead.
func (*SharedFileInfo) Descriptor() ([]byte, []int) {
	return file_sharing_proto_rawDescGZIP(), []int{3}
}

func (x *SharedFileInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SharedFileInfo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *SharedFileInfo) GetSharedAt() int64 {
	if x != nil {
		return x.SharedAt
	}
	return 0
}

type GetSharedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*SharedFileInfo      `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSharedResponse) Reset() {
	*x = GetSharedResponse{}
	mi := &file_sharing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSharedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSharedResponse) ProtoMessage() {}

func (x *GetSharedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sharing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSharedResponse.ProtoReflect.Descriptor instead.
func (*GetSharedResponse) Descriptor() ([]byte, []int) {
	return file_sharing_proto_rawDescGZIP(), []int{4}
}

func (x *GetSharedResponse) GetFiles() []*SharedFileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

type CreateLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkRequest) Reset() {
	*x = CreateLinkRequest{}
	mi := &file_sharing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkRequest) ProtoMessage() {}

func (x *CreateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateLinkRequest) Descriptor() ([]byte, []int) {
	return file_sharing_proto_rawDescGZIP(), []int{5}
}

func (x *CreateLinkRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CreateLinkRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *CreateLinkRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type CreateLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkResponse) Reset() {
	*x = CreateLinkResponse{}
	mi := &file_sharing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkResponse) ProtoMessage() {}

func (x *CreateLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sharing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateLinkResponse) Descriptor() ([]byte, []int) {
	return file_sharing_proto_rawDescGZIP(), []int{6}
}

func (x *CreateLinkResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *CreateLinkResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateLinkResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_sharing_proto protoreflect.FileDescriptor

const file_sharing_proto_rawDesc = "" +
	"\n" +
	"\rsharing.proto\x12\tsharingpb\"a\n" +
	"\fShareRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1f\n" +
	"\vshared_with\x18\x03 \x01(\tR\n" +
	"sharedWith\"Y\n" +
	"\rShareResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\".\n" +
	"\x10GetSharedRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"_\n" +
	"\x0eSharedFileInfo\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x1b\n" +
	"\tshared_at\x18\x03 \x01(\x03R\bsharedAt\"D\n" +
	"\x11GetSharedResponse\x12/\n" +
	"\x05files\x18\x01 \x03(\v2\x19.sharingpb.SharedFileInfoR\x05files\"f\n" +
	"\x11CreateLinkRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"]\n" +
	"\x12CreateLinkResponse\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt2\xe8\x01\n" +
	"\x0eSharingService\x12>\n" +
	"\tShareFile\x12\x17.sharingpb.ShareRequest\x1a\x18.sharingpb.ShareResponse\x12K\n" +
	"\x0eGetSharedFiles\x12\x1b.sharingpb.GetSharedRequest\x1a\x1c.sharingpb.GetSharedResponse\x12I\n" +
	"\n" +
	"CreateLink\x12\x1c.sharingpb.CreateLinkRequest\x1a\x1d.sharingpb.CreateLinkResponseBKZIgithub.com/spbu-ds-practicum-2025/vanya-and-co/services/sharing/sharingpbb\x06proto3"

var (
	file_sharing_proto_rawDescOnce sync.Once
	file_sharing_proto_rawDescData []byte
)

func file_sharing_proto_rawDescGZIP() []byte {
	file_sharing_proto_rawDescOnce.Do(func() {
		file_sharing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sharing_proto_rawDesc), len(file_sharing_proto_rawDesc)))
	})
	return file_sharing_proto_rawDescData
}

var file_sharing_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sharing_proto_goTypes = []any{
	(*ShareRequest)(nil),       // 0: sharingpb.ShareRequest
	(*ShareResponse)(nil),      // 1: sharingpb.ShareResponse
	(*GetSharedRequest)(nil),   // 2: sharingpb.GetSharedRequest
	(*SharedFileInfo)(nil),     // 3: sharingpb.SharedFileInfo
	(*GetSharedResponse)(nil),  // 4: sharingpb.GetSharedResponse
	(*CreateLinkRequest)(nil),  // 5: sharingpb.CreateLinkRequest
	(*CreateLinkResponse)(nil), // 6: sharingpb.CreateLinkResponse
}
var file_sharing_proto_depIdxs = []int32{
	3, // 0: sharingpb.GetSharedResponse.files:type_name -> sharingpb.SharedFileInfo
	0, // 1: sharingpb.SharingService.ShareFile:input_type -> sharingpb.ShareRequest
	2, // 2: sharingpb.SharingService.GetSharedFiles:input_type -> sharingpb.GetSharedRequest
	5, // 3: sharingpb.SharingService.CreateLink:input_type -> sharingpb.CreateLinkRequest
	1, // 4: sharingpb.SharingService.ShareFile:output_type -> sharingpb.ShareResponse
	4, // 5: sharingpb.SharingService.GetSharedFiles:output_type -> sharingpb.GetSharedResponse
	6, // 6: sharingpb.SharingService.CreateLink:output_type -> sharingpb.CreateLinkResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sharing_proto_init() }
func file_sharing_proto_init() {
	if File_sharing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sharing_proto_rawDesc), len(file_sharing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sharing_proto_goTypes,
		DependencyIndexes: file_sharing_proto_depIdxs,
		MessageInfos:      file_sharing_proto_msgTypes,
	}.Build()
	File_sharing_proto = out.File
	file_sharing_proto_goTypes = nil
	file_sharing_proto_depIdxs = nil
}
